### ISSUE TITLE
TechReborn Support

### ISSUE THREAD

**Issue by KenyMylankca** [Shovinus/ChopDown#41]
Can you add support for TechReborn's Rubber Wood please? Thanks!

**Comment by Shovinus** [comment]
added
https://docs.google.com/spreadsheets/d/1DtrXzFRpJuTopPSMFDlWys92Sg8raGmw_nHC4ot0iNE/edit#gid=0
will be in next release.

**Comment by KenyMylankca** [comment]
_config addition? i didn't understand that._
edit: oh, so sorry, i forgot that this isn't techreborn's github.
