### ISSUE TITLE
Can't get custom config to work for Bewitchment mod

### ISSUE THREAD

**Issue by Zygus42** [Shovinus/ChopDown#50]
This is what my config line looks like:
    S:customTrees <
{"logs":["bewitchment:cypress_wood","bewitchment:elder_wood","bewitchment:juniper_wood","bewitchment:yew_wood"], "leaves":["bewitchment:cypress_leaves","bewitchment:elder_leaves","bewitchment:juniper_leaves","bewitchment:yew_leaves"]}
     >

But nothing happens with any of the trees when you chop them down.

chopdownupdated-1.12.2-1.2.4
bewitchment-1.12.2-0.0.20.6
forge-1.12.2-14.23.5.2838-installer-win

**Comment by Shovinus** [comment]
Think you are missing the .* Off

**Comment by Zygus42** [comment]
No idea what you mean by that.  What should it look like ?

**Comment by Shovinus** [comment]
The string is regex compared to [mod]:[block name]:[damagevalue]
To match with any damage value you need to put "bewitchment:cypress_wood:.\*" (example) as ".\*" matches any character and any number of times.

**Comment by Zygus42** [comment]
This didn't work either:
    S:customTrees <
        {"logs":["bewitchment:cypress_wood:.*","bewitchment:elder_wood:.*","bewitchment:juniper_wood.*","bewitchment:yew_wood:,*"], "leaves":["bewitchment:cypress_leaves","bewitchment:elder_leaves","bewitchment:juniper_leaves","bewitchment:yew_leaves"]}
     >

**Comment by Zygus42** [comment]
Odd - in  my config it has .*, but none of the * copied over.

**Comment by Zygus42** [comment]
S:customTrees <
        {"logs":["bewitchment:cypress_wood:.*","bewitchment:elder_wood:.*","bewitchment:juniper_wood.*","bewitchment:yew_wood:,*"], "leaves":["bewitchment:cypress_leaves","bewitchment:elder_leaves","bewitchment:juniper_leaves","bewitchment:yew_leaves"]}
     >

**Comment by Zygus42** [comment]
Fixed to this, still not working:   

 S:customTrees <
        {"logs":["bewitchment:cypress_wood:.*","bewitchment:elder_wood:.*","bewitchment:juniper_wood:.*","bewitchment:yew_wood:*"], "leaves":["bewitchment:cypress_leaves","bewitchment:elder_leaves","bewitchment:juniper_leaves","bewitchment:yew_leaves"]}
     >

**Comment by Shovinus** [comment]
same principle for the leaves mate,
`{"logs":["bewitchment:cypress_wood:.*","bewitchment:elder_wood:.*","bewitchment:juniper_wood:.*","bewitchment:yew_wood:.*"], "leaves":["bewitchment:cypress_leaves:.*","bewitchment:elder_leaves:.*","bewitchment:juniper_leaves:.*","bewitchment:yew_leaves:.*"]}`

**Comment by Zygus42** [comment]
S:customTrees <
        {"logs":["bewitchment:cypress_wood:.*","bewitchment:elder_wood:.*","bewitchment:juniper_wood:.*","bewitchment:yew_wood:*"], "leaves":["bewitchment:cypress_leaves:.*","bewitchment:elder_leaves:.*","bewitchment:juniper_leaves:.*","bewitchment:yew_leaves:.*"]}
     >

This is now working for all but the Yew, which is a 2x2 tree - does anything need to be changed to make that one work ?

**Comment by Shovinus** [comment]
https://docs.google.com/spreadsheets/d/1rd5sj0zlvObrYgwUS9MVBMSZPFP5BcICQsirCJ8pmCg/edit#gid=0

You are actually defining multiple blocks for 1 tree btw which is wrong, it will work but the system wont be able to determine the difference between trees

Make a copy of this spreadsheet and define it properly

For 2x2 trees you need to cut all the way through the trunk, if you are doing use the showBlockName command to determine the blocks actual names as possibly you have them wrong

**Comment by Zygus42** [comment]
Yep, looked at at spreadsheet before, and haven't got clue one what to do with it.

No clue what you mean by "You are actually defining multiple blocks for 1 tree btw which is wrong, it will work but the system wont be able to determine the difference between trees".

Did chop through all the wood blocks at ground level for the yew.

 Nope, that's the name of the Yew block and the Yew leaves.

**Comment by Shovinus** [comment]
https://docs.google.com/spreadsheets/d/1nIT-NxYNJRdN_HWCBvpMuSnv9qhZKcfQkm0wi-6YTto/edit#gid=0

```
{"logs":["bewitchment:cypress_wood:.*"], "leaves":["bewitchment:cypress_leaves:.*"]}
{"logs":["bewitchment:elder_wood:.*"], "leaves":["bewitchment:elder_leaves:.*"]}
{"logs":["bewitchment:juniper_wood:.*"], "leaves":["bewitchment:juniper_leaves:.*"]}
{"trunk_radius":2, "logs":["bewitchment:yew_wood:.*"], "leaves":["bewitchment:yew_leaves:.*"]}
```

**Comment by Zygus42** [comment]
I see, each tree is it's own line.

And yes, this works.  Thanks for the assistance.

Ought to get this mod added as a standard.
